Database week2
aladdin91/hyf-homework pull request #16
Opened 2023-01-21 11:19 UTC by aladdin91

this is my homework for database week2

2023-01-21 17:49 UTC, dboyadzhiev requested changes
Good Job! 

pls, read a bit more about 
`CONSTRAINT ... FOREIGN KEY ... REFERENCES ... ON DELETE CASCADE`
https://www.geeksforgeeks.org/mysql-on-delete-cascade-constraint/

2023-01-21 17:49 UTC, dboyadzhiev commented on databases/week2/part4.sql
> +        password int(10) NOT NULL,
So the password can contain only numbers? 
what about `pass1234`

2023-01-21 17:49 UTC, dboyadzhiev commented on databases/week2/part4.sql
> +        favourite_author_id int(10) unsigned NOT NULL,
what if a user doesn't have any favorite book and/or author?

2023-01-21 17:49 UTC, dboyadzhiev commented on databases/week2/part4.sql
> +        CONSTRAINT fav_author FOREIGN KEY (favourite_author_id) REFERENCES author(id) ON DELETE CASCADE
This says: when a book is deleted, delete the connected users. 
Is that what you want?

2023-01-21 17:49 UTC, dboyadzhiev commented on databases/week2/part4.sql
> +        category_name varchar(255) NOT NULL,
what about `category_id`? does it do the same?

2023-01-21 17:49 UTC, dboyadzhiev commented on databases/week2/part4.sql
> +        isbn int NOT NULL,
this could be unique, `isbn` is a unique book identifier.  It could be used as a primary key but I wouldn't.

2023-01-21 17:49 UTC, dboyadzhiev commented on databases/week2/part4.sql
> +        rating_id int(10) unsigned NOT NULL,
what if the book had not been rated yet?

2023-01-21 17:49 UTC, dboyadzhiev commented on databases/week2/part4.sql
> +        CONSTRAINT rating FOREIGN KEY (rating_id) REFERENCES rating(id) ON DELETE CASCADE,
This says: when a category is deleted, delete the connected books.
Is that what you want?

2023-01-21 17:49 UTC, dboyadzhiev commented on databases/week2/part1.sql
> +DELETE FROM task WHERE id = '15';
the `id` column is an integer  

`id = '15'` should be `id = 15`

2023-01-21 17:49 UTC, dboyadzhiev commented on databases/week2/part3.sql
> +    DATE_FORMAT(task.created, '%M');
```suggestion
GROUP BY
    DATE_FORMAT(task.created, '%M');
```

2023-01-21 17:49 UTC, dboyadzhiev commented on databases/week2/part2.sql
> +-- Get all the tasks assigned to users whose email ends in @spotify.com
duplicated code with `part3.sql` :)

2023-01-21 18:48 UTC, aladdin91 commented
> Good Job!
> 
> pls, read a bit more about `CONSTRAINT ... FOREIGN KEY ... REFERENCES ... ON DELETE CASCADE` https://www.geeksforgeeks.org/mysql-on-delete-cascade-constraint/

thanks for the review and the link, i did modify the homework :)

2023-01-25 19:12 UTC, dboyadzhiev approved these changes

2023-01-31 17:57 UTC, merged